import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import vm from "node:vm";
import ts from "typescript";

const routePath = path.join(path.dirname(fileURLToPath(import.meta.url)), "../app/api/cron/attendance-approved-submissions/route.ts");
const source = fs.readFileSync(routePath, "utf8");
const compiled = ts.transpileModule(source, {
  compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 },
}).outputText;

const dayKey = (date) => {
  const shifted = new Date(date.getTime() + 7 * 60 * 60 * 1000);
  return new Date(Date.UTC(shifted.getUTCFullYear(), shifted.getUTCMonth(), shifted.getUTCDate()));
};
const tenantA = "11111111-1111-4111-8111-111111111111";
const tenantB = "22222222-2222-4222-8222-222222222222";

function loadRoute(rows, submissions) {
  const prisma = {
    attendance: {
      findMany: async ({ where }) => rows
        .filter((row) => row.tenantId === where.tenantId && row.attendanceDay <= where.attendanceDay.lte &&
          row.status === where.status && row.notes === where.notes &&
          row.checkIn === null && row.checkOut === null)
        .map(({ id, userId, attendanceDay }) => ({ id, userId, attendanceDay })),
      updateMany: async ({ where, data }) => {
        const row = rows.find((item) => item.id === where.id);
        if (!row || row.tenantId !== where.tenantId || row.status !== where.status || row.notes !== where.notes ||
            row.checkIn !== null || row.checkOut !== null) return { count: 0 };
        Object.assign(row, data);
        return { count: 1 };
      },
    },
    submission: {
      findMany: async ({ where }) => submissions.filter((item) =>
        item.tenantId === where.tenantId && item.status === where.status && where.userId.in.includes(item.userId) &&
        item.startDate < where.startDate.lt && item.endDate >= where.endDate.gte),
    },
  };
  const modules = {
    "next/server": { NextResponse: { json: (body, options) => ({ body, status: options?.status ?? 200 }) } },
    "@/lib/prisma": { default: prisma },
    "@/lib/helper/date": { getJakartaDayKey: dayKey },
    "@/lib/helper/submission-attendance": {
      AUTO_ABSENT_NOTE: "Auto generated by cron",
      AUTO_SUBMISSION_ATTENDANCE_NOTE: "Auto generated by cron from approved submission",
    },
  };
  const exports = {};
  vm.runInNewContext(compiled, {
    exports,
    require: (name) => modules[name],
    process: { env: { CRON_SECRET: "test-secret" } },
    Date,
    console,
  });
  return exports.POST;
}

test("late approval changes only the matching automatic absence and is idempotent", async () => {
  const today = dayKey(new Date());
  const sickDay = new Date(today);
  sickDay.setUTCDate(sickDay.getUTCDate() - 2);
  const requestDate = new Date(sickDay.getTime() - 7 * 60 * 60 * 1000);
  const rows = [
    { id: "sick", tenantId: tenantA, userId: "user-a", attendanceDay: sickDay, status: "Absent", notes: "Auto generated by cron", checkIn: null, checkOut: null },
    { id: "other", tenantId: tenantA, userId: "user-b", attendanceDay: sickDay, status: "Absent", notes: "Auto generated by cron", checkIn: null, checkOut: null },
    { id: "manual", tenantId: tenantA, userId: "user-a", attendanceDay: new Date(sickDay.getTime() - 86400000), status: "Absent", notes: "Changed by admin", checkIn: null, checkOut: null },
    { id: "other-tenant", tenantId: tenantB, userId: "user-a", attendanceDay: sickDay, status: "Absent", notes: "Auto generated by cron", checkIn: null, checkOut: null },
  ];
  const submissions = [
    { tenantId: tenantA, userId: "user-a", status: "APPROVED", startDate: requestDate, endDate: requestDate, submissionType: { name: "Sakit" } },
    { tenantId: tenantB, userId: "user-a", status: "APPROVED", startDate: requestDate, endDate: requestDate, submissionType: { name: "Cuti" } },
  ];
  const POST = loadRoute(rows, submissions);
  const authorized = { headers: { get: () => "Bearer test-secret" }, json: async () => ({ tenantId: tenantA }) };

  const first = await POST(authorized);
  assert.equal(first.status, 200);
  assert.equal(first.body.checked, 2);
  assert.equal(first.body.updated, 1);
  assert.equal(rows[0].status, "Sakit");
  assert.equal(rows[1].status, "Absent");
  assert.equal(rows[2].status, "Absent");
  assert.equal(rows[3].status, "Absent");

  const second = await POST(authorized);
  assert.equal(second.body.updated, 0);
  const otherTenant = await POST({ headers: authorized.headers, json: async () => ({ tenantId: tenantB }) });
  assert.equal(otherTenant.body.updated, 1);
  assert.equal(rows[3].status, "Cuti");
  assert.equal((await POST({ headers: { get: () => "Bearer wrong" } })).status, 401);
  assert.equal((await POST({ headers: authorized.headers, json: async () => ({ tenantId: "invalid" }) })).status, 400);
});
