name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e

            echo "🚀 Start deploy..."

            # Load NVM
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            nvm use 24

            cd /home/jaxerid/jaxer-project/production/hr-manage-next

            echo "📥 Pull latest code"
            git pull origin production

            echo "📦 Install dependencies"
            npm install

            echo "⚙️ Generate Prisma Client (SAFE)"
            npx prisma generate

            echo "🏗️ Build app"
            npm run build

            echo "🔄 Reload PM2"
            pm2 reload jahris-prod-next

            echo "✅ Deploy success 🚀"
          EOF
